title: "Dev Log - Andre Sampaio"
description: "Atualizações automáticas dos meus projetos de desenvolvimento"
url: "https://AndreMicael.github.io"
baseurl: "/blog-eucomittei"
author:
  name: "Andre Sampaio"

plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true

date_format: "%d/%m/%Y"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
